# Generated by Django 5.0.7 on 2024-07-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='No details given', verbose_name='Details'),
        ),
    ]
