# Generated by Django 5.0.7 on 2024-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(default='Product detail', verbose_name='Details'),
        ),
    ]
