# Generated by Django 5.0.7 on 2024-07-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('ratings', models.IntegerField(choices=[(1, 'Excelent'), (2, 'Good'), (3, 'Bad')])),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
            ],
        ),
    ]
