# Generated by Django 5.0.7 on 2024-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_feedback_email_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
