# Generated by Django 5.0.7 on 2024-07-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=10),
        ),
    ]
