# Generated by Django 5.0.7 on 2024-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_feedback_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.IntegerField(choices=[(1, 'Excelent'), (2, 'Good'), (3, 'Bad')], max_length=10),
        ),
    ]
