# Generated by Django 5.0.7 on 2024-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_category_product_prod_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_address',
            field=models.CharField(default='address', max_length=10, verbose_name='Seller Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.EmailField(default='abc@gmail.com', max_length=50, verbose_name='Seller Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='abc', max_length=50, verbose_name='Seller Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(default=1234567890, max_length=10, verbose_name='Seller Phone'),
            preserve_default=False,
        ),
    ]
