# Generated by Django 5.0.7 on 2024-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_seller_address_product_seller_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_address',
            field=models.TextField(max_length=10, verbose_name='Seller Address'),
        ),
    ]
