# Generated by Django 5.0.7 on 2024-07-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_prod_category_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='age',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
    ]
