# Generated by Django 5.0.7 on 2024-07-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_feedback_age_remove_feedback_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_phone',
        ),
    ]
